# fly.toml app configuration file generated for slowwave on 2024-10-03T16:49:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'slowwave'
primary_region = 'cdg'
console_command = '/rails/bin/rails console'

[build]

[[services]]
  internal_port = 3000
  internal_address = "0.0.0.0"
  protocol = "tcp"

[[services.http_checks]]
  path = "/"
  method = "get"
  interval = "15s" # Increased to allow more time between checks
  timeout = "5s"  # Increased to allow more response time
  grace_period = "10s"
  protocol = "http"
  restart_limit = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

